# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e18ab830be92ed81ade2873834a8ad3bb01acccf9d5d82a973f6ba373d2e885791d9791cb2ab62bd3abab8328417944c8940e11505fe9e9ae6573cc4167a41e7

test:
  secret_key_base: a43a19b8877852b6241c30609c5c01cece39affc718363cf25d6760097e2200c985dba724443f8458231c97d044c4904ca40c53f0389d28c3569f4a394722e76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
